--DROP USER IMBISS;

-- CREATE Table-Spaces
CREATE TABLESPACE ts_imbiss
DATAFILE 'imbiss_ts.dbf'
SIZE 1m
AUTOEXTEND ON NEXT 20m;


-- CREATE Users
CREATE USER Imbiss IDENTIFIED BY imbiss
DEFAULT TABLESPACE ts_imbiss;

GRANT DELETE ANY TABLE TO imbiss;
GRANT CREATE ANY TABLE TO imbiss;
GRANT DROP ANY TABLE TO imbiss;
GRANT ALTER ANY TABLE TO imbiss;
GRANT UPDATE ANY TABLE TO imbiss;
GRANT CREATE SESSION TO imbiss;
GRANT UNLIMITED TABLESPACE TO imbiss;

CREATE USER ImbissMitarbeiter IDENTIFIED BY imbiss
DEFAULT TABLESPACE ts_imbiss;
